import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className="p-24">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="">{children}</div>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
type RootLayoutProps = {
  children: React.ReactNode;
};
